### ISSUE TITLE
remove_submenu_page issue in multisite mode

### ISSUE THREAD

**Issue by emfluenceindia** [vincentorback/clean-wordpress-admin#3]
I tried to remove a sub menu page by using
`remove_submenu_page( 'admin.php', 'admin.php?page=yrc_home_settings_page' );` but it did not work. the sub menu still stays there.

If I use remove_submenu_page( 'yrc_home_settings_page', 'yrc_home_settings_page' ); it takes away all submenus under YRC Settings parent menu when it supposed to remove only the one I wanted.

The same approach i.e. `remove_submenu_page( 'yrc_home_settings_page', 'yrc_home_settings_page' );` works well in single installation mode.

WP Version: 4.8
Multisite: Yes
Theme: VIP

**Comment by vincentorback** [comment]
Hmm before I take a look at this myself, could you try something suggested in this [stackoverflow thread](https://stackoverflow.com/questions/44800905/how-to-remove-sub-menu-page-in-wp-admin-which-uses-admin-php-and-a-query-string)? 
Looks like they suggest using `remove_submenu_page( 'yrc_settings_page', 'yrc_home_settings_page' );`

Also I don’t know what `yrc_settings_page` is so I can’t really test it specifically. Does `remove_submenu_page` work with other pages on multisite?

**Comment by emfluenceindia** [comment]
Thanks for your reply. [Mentioned thread](https://stackoverflow.com/questions/44800905/how-to-remove-sub-menu-page-in-wp-admin-which-uses-admin-php-and-a-query-string) was also opened by me however the issue was a bit different there which I figured out later. I have also figured this out with multisite that I need to use `admin_init` hook rather than using `admin_menu` hook which I was previously using!

Here is my code:
```
function remove_submenu_item() {
    if(!is_super_admin()) {
         // remove_submenu_page($parent_slug, $menu_slug);
         remove_submenu_page('yrc_settings_page', 'yrc_home_settings_page');
    }
}

add_action('admin_init', 'remove_submenu_item', 999)
```
Previously I was using `add_action('admin_menu', 'remove_submenu_item', 999)`

**Comment by anas-khalid** [comment]
Sorry, I am bit late here but using `admin_init` hook will have given you `PHP Warning:  Invalid argument supplied for foreach()` warning.
`admin_menu` doesn't give such warnings. Is it safe to ignore these warnings or there is a better way of doing this?

**Comment by vincentorback** [comment]
@anas-khalid hmm since there is no `foreach()` in this repo, maybe it's something else going wrong? Can you share some code?
