### ISSUE TITLE
contextual_help is deprecated since version 3.3.0

### ISSUE THREAD

**Issue by tiendungdev** [vincentorback/clean-wordpress-admin#5]
contextual_help is deprecated since version 3.3.0?

How to fix bro?

**Comment by vincentorback** [comment]
Hmm I just tested on version 5.4 with the functions from [https://github.com/vincentorback/clean-wordpress-admin/blob/master/contextual-tabs.php](contextual-tabs.php) and they seem to work fine.

[Reading here I understand it as they were just moved](https://codex.wordpress.org/Adding_Contextual_Help_to_Administration_Menus#Adding_The_Contextual_Help_Tabs_.28post_3.3.29) and I think functions to remove tabs still work, not sure if adding tabs still works.

What’s not working for you?

**Comment by vincentorback** [comment]
Woops, just got the error. Updated [contextual-tabs.php](https://github.com/vincentorback/clean-wordpress-admin/blob/master/contextual-tabs.php) now, thanks for the input :)
